INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (1, 'Arizona Diamondbacks', 'ARI');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (2, 'Atlanta Braves', 'ATL');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (3, 'Baltimore Orioles', 'BAL');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (4, 'Boston Red Sox', 'BOS');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (5, 'Chicago Cubs', 'CHC');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (7, 'Cincinnati Reds', 'CIN');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (8, 'Cleveland Indians', 'CLE');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (9, 'Colorado Rockies', 'COL');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (10, 'Detroit Tigers', 'DET');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (11, 'Houston Astros', 'HOU');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (13, 'Los Angeles Angels of Anaheim', 'LAA');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (14, 'Los Angeles Dodgers', 'LAD');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (15, 'Miami Marlins', 'MIA');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (16, 'Milwaukee Brewers', 'MIL');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (17, 'Minnesota Twins', 'MIN');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (18, 'New York Mets', 'NYM');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (19, 'New York Yankees', 'NYY');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (20, 'Oakland Athletics', 'OAK');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (21, 'Philadelphia Phillies', 'PHI');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (22, 'Pittsburgh Pirates', 'PIT');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (23, 'San Diego Padres', 'SD');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (24, 'Seattle Mariners', 'SEA');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (26, 'St. Louis Cardinals', 'STL');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (27, 'Tampa Bay Rays', 'TB');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (28, 'Texas Rangers', 'TEX');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (29, 'Toronto Blue Jays', 'TOR');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (30, 'Washington Nationals', 'WAS');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (25, 'San Francisco Giants', 'SF');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (12, 'Kansas City Royals', 'KC');
INSERT INTO public.team (team_id, team_name, team_code_mlb) VALUES (6, 'Chicago White Sox', 'CWS');